### ISSUE TITLE
two-cols layout is missing a gap between the two columns when code blocks are side by side

### ISSUE THREAD

**Issue by louim** [slidevjs/themes#14]
Hello!  Not sure if this is the correct repo to report this, feel free to move the issue. I noticed a small theme problem using `two-cols` layouts. It seems that two code box get very close together when they are in their own columns.

~~~
---
layout: two-cols-header
---

# Exception Handling

::left::

```ruby
def divide(x, y)
  x / y
rescue ZeroDivisionError => e
  puts "Error: #{e.message}"
end
```

::right::

```ruby
class Person
  attr_accessor :name, :age

  def initialize(name, age)
    @name = name
    @age = age
  end
end

person = Person.new("Alice", 30)
```

---
~~~

This is what it looks like using the `seriph` theme. I haven't tried the other, but I guess they might have the same problem.
<img width="1341" alt="image" src="https://github.com/slidevjs/themes/assets/923718/d080fdd5-425f-4842-9222-18ff5810e21f">

**Comment by antfu** [comment]
It's intentional to leave that to users to define (it's easier to add padding than removing).

You can use `calss: gap-2` in frontmatter to configure it, or wrap the inner content with padding - up to you!
