### ISSUE TITLE
Seriph theme should load bold and italic styles as well

### ISSUE THREAD

**Issue by 747** [slidevjs/themes#9]
``` markdown
# **Welcome** to *Slidev*

Presentation slides for developers
```

results in the following rendering (just using the starter template):
![image](https://user-images.githubusercontent.com/3427854/179564912-b32f3cea-52a7-421f-9f98-0c9546a56e1d.png)

It apparently shows fake boldface and italic fallbacks rather than the true glyphs [the font](https://fonts.google.com/specimen/PT+Serif) is supposed to have.
![image](https://user-images.githubusercontent.com/3427854/179565704-345df027-e0d8-407d-9c3f-3b0b7dca253d.png)

Of course I can add a line in the style.css as follows to easily make them work:
``` css
@import url('https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap');
```
but considering it is one of the default themes, out-of-box support would be appreciated as well as appropriate.

**Comment by antfu** [comment]
Nice catch! PR welcome
